// The ONE definition of the two production bundles (Obsidian plugin, Node CLI). esbuild.config.mjs builds from these
// objects and tools/hook-isolation.mjs checks the same objects, so the isolation check cannot drift from the build.
import { join, resolve } from "node:path";
import builtins from "builtin-modules";

const banner = `/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
if you want to view the source, please visit the github repository of this plugin
*/
`;

export const CLI_OUT = "dist/cli/ipfs-sync.mjs";

/** Where the plugin bundle goes. A production build always writes dist/plugin/ and never touches a vault. */
export function pluginOutDir(prod, env = process.env) {
  return prod || !env.OBSIDIAN_PLUGIN_DIR ? "dist/plugin" : resolve(env.OBSIDIAN_PLUGIN_DIR);
}

// Obsidian plugin bundle: WebView target (desktop and mobile).
export function pluginOptions(prod, outDir = pluginOutDir(prod)) {
  return {
    banner: { js: banner },
    entryPoints: ["src/main.ts"],
    bundle: true,
    external: ["obsidian", "electron", ...builtins],
    format: "cjs",
    target: "es2022",
    logLevel: "info",
    sourcemap: prod ? false : "inline",
    treeShaking: true,
    outfile: join(outDir, "main.js"),
  };
}

// Node 24 CLI: a single ESM file, `bin: ipfs-sync`. CommonJS dependencies that call require() get a createRequire shim.
export function cliOptions(prod) {
  return {
    banner: {
      js: [
        "#!/usr/bin/env node",
        'import { createRequire as __createRequire } from "node:module";',
        "const require = __createRequire(import.meta.url);",
      ].join("\n"),
    },
    entryPoints: ["cli/main.ts"],
    bundle: true,
    platform: "node",
    format: "esm",
    target: "node24",
    logLevel: "info",
    sourcemap: prod ? false : "inline",
    treeShaking: true,
    outfile: CLI_OUT,
  };
}
