export const HELP_TEXT = `ipfs-sync - vault sync over your own kubo node

Usage:
  ipfs-sync status [options]
  ipfs-sync init <vault> [--passphrase-file <path>] [options]
  ipfs-sync publish <vault> [options]
  ipfs-sync pull <vault> [options]
  ipfs-sync abandon <vault> [--yes-abandon] [options]

Commands:
  status                  Show node identity, MFS listing, gateway fetch, write probe and key state.
  init <vault>            Create the encrypted vault for <vault> in the MFS root (the only command that creates one).
                          The passphrase is generated by init (25 characters, five groups of five) and is never
                          chosen by you. On a terminal it is shown once and you must type it again; what is shown
                          stays in the terminal scrollback and in the logs of tools such as script and tmux, so
                          clear or disable those first, or use --passphrase-file. With
                          --passphrase-file <path> it is written to a new file (mode 0600, created exclusively;
                          an existing file, a symbolic link, or a directory that is a symbolic link, belongs to
                          another user or is writable by others without a sticky bit is refused) and only the path
                          is printed, so automation can then publish with IPFS_SYNC_PASSPHRASE_FILE=<path>. A passphrase in the environment is
                          ignored. There is no recovery: a lost passphrase means the data is lost for good.
                          Windows has no POSIX file modes: the file inherits its folder's access list and the
                          check cannot be made there (init says so before writing).
  publish <vault>         Encrypt and send only the changed files of <vault> to the node, then publish the
                          snapshot to the IPNS key. Every publish is encrypted and needs the vault passphrase;
                          a vault is created by "ipfs-sync init", never by publish. Only fixture vaults (marker
                          file .ipfs-sync-fixture containing the text "fixture") are accepted until encryption
                          has been independently reviewed; a marker written by pull ("pulled-fixture"), an empty
                          marker or none is refused before any request. Creates the key when it does not exist
                          yet and records its ID in the config file (ownedKeys).
  pull <vault>            Bring <vault> to the published state of an encrypted vault by fetching only missing or
                          changed files. It needs the vault passphrase (see "Unlocking a vault") and takes the same
                          publish.lock as publish. The manifest is authenticated before any file is requested; every
                          file is decrypted and hashed before it appears; local edits are kept as
                          "<name> (ipfs conflict YYYY-MM-DD).<ext>" and never deleted; remote deletions are only
                          reported. A sequence lower than the one this device recorded is refused unless you restore
                          it on purpose (--allow-rollback with --root-cid or --manifest). Reads only (name resolve,
                          gateway); writes nothing to the node. The first pull of a vault on this device shows the
                          sequence, date and device the vault key holder chose and asks (or needs --accept-first-pull).
                          Output lists integrity-failed files, files not fetched and skipped paths apart. The
                          destination must be absent, empty or hold the .ipfs-sync-fixture marker ("fixture" or
                          "pulled-fixture") until encryption has been independently reviewed (a pulled fresh directory
                          gets "pulled-fixture", which pull accepts and publish refuses). A root that holds a plaintext
                          (version 1) manifest is read only with --allow-plaintext-v1, as before.
  abandon <vault>         Abandon this device's vault for the MFS root: move the local key-slot copy, sync state and
                          journal (.ipfs-sync/keyslots.<h>.json, state.<h>.json, journal.<h>.json) into
                          .ipfs-sync/abandoned-<h>-<time>/, keeping them as a backup. Use it when a refusal says to
                          abandon this vault (the node lost the key slots, or its state cannot be repaired). It never
                          contacts the node and deletes nothing; afterwards create a new vault with init in an empty
                          MFS root (a new --mfs-root). On a terminal it shows what will move and asks you to type the
                          word "abandon"; without a terminal it does nothing unless --yes-abandon is given.

Options:
  --config <path>         Config file (default ./ipfs-sync.config.json if present). Endpoints and
                          non-secret fields only; secrets are rejected.
  --rpc-url <url>         RPC (write) endpoint.
  --rpc-port <port>       RPC port, applied to --rpc-url.
  --gateway-url <url>     Gateway (read) endpoint.
  --gateway-port <port>   Gateway port, applied to --gateway-url.
  --mfs-root <path>       MFS root; must be /obsidian-vault-sync or below it (default /obsidian-vault-sync/default).
                          publish needs a root strictly below /obsidian-vault-sync.
  --key <name>            IPNS publication key name; must match ^obsidian-vault(-[a-z0-9-]+)?$
                          (default obsidian-vault-sync).
  --owned-key <id>        IPNS key ID this installation owns (repeatable). For this run only; never written
                          to the config file.
  --passphrase-file <p>   init: write the generated passphrase to this new file (0600). There is no --passphrase
                          option: a passphrase on the command line would show in the process list and shell history.
  --auth <scheme>         none | basic | bearer | header.
  --auth-user <user>      basic: user.
  --auth-password <pw>    basic: password.
  --auth-token <token>    bearer: static token or JWT.
  --auth-header-name <n>  header: header name.
  --auth-header-value <v> header: header value.
  --name <id>             pull: IPNS key ID to pull from (default: the ID of the owned key given by --key).
  --root-cid <cid>        pull: pull this immutable root instead of the name. The client does not verify the bytes the
                          gateway returns against the CID; authenticity rests on the vault key.
  --manifest <cid>        pull: read the history entry whose manifest names this tree CID (manifests/<sequence>-<cid>.enc or
                          <cid>.enc) under the root the name serves. For a plaintext root: the snapshot published when
                          current/ had this CID (manifests/<cid>.json).
  --manifest-file <path>  pull: plaintext reader only: read the manifest from a local file. --manifest, --manifest-file
                          and --root-cid exclude each other.
  --allow-rollback        pull: accept an older sequence as a restore. Needs --root-cid or --manifest; never accepted for
                          the name. A restore adds and replaces files and never deletes; the recorded highest sequence
                          stays, and the next publish makes the result a new version.
  --resolve-fork          pull: another device published the same sequence with other content. Asks first on a terminal
                          (it needs one). Where both devices changed a file, this device's text is kept as a dated conflict
                          copy; files only this device changed stay and are published next. Name target only.
  --expect-min-sequence <n>  pull: refuse a manifest whose sequence is below n.
  --expect-vault-id <id>  pull: refuse unless the vault id (32 lowercase hex characters) matches; checked before any key
                          derivation.
  --accept-first-pull     pull: the non-interactive yes to the first-pull question. Without a terminal a first pull is
                          refused without it.
  --max-bytes <n>         pull: ask before fetching more than n bytes of file content (default 536870912, 512 MiB).
  --accept-large          pull: the non-interactive yes to that question. Without a terminal a larger pull fetches nothing
                          and exits 1 without it.
  --list-versions         pull: print the newest 20 history entries by name (the sequence comes from the name; names
                          written before the sequence prefix come last), with date and device for each file of at most
                          8 MiB after unlocking. Reads only; writes nothing.
  --allow-plaintext-v1    pull: allow reading a plaintext (version 1) manifest, which anyone who can write to the node can
                          forge. Never honoured for a destination that has seen an encrypted vault. The same path
                          policy as the encrypted reader applies: .obsidian/, .git/ and .ipfs-sync/ in any spelling
                          (case, look-alike or invisible characters, trailing dot or space, 8.3 short names),
                          Windows device names, colons, control characters and case collisions are refused, counted
                          as failed (exit 1), and never fetched. The CLI knows only the default configuration folder
                          name; a renamed Obsidian configuration folder is not protected by the CLI.
  --break-lock            publish: remove the publish lock in the vault's .ipfs-sync folder after a confirmation, then
                          continue. A lock is taken over automatically when its process is gone from this host, or when
                          it has had no heartbeat for 15 minutes. The lock is a best-effort guard, not atomic across machines.
  --repair                publish: continue past a "node is behind" or "node is ahead" refusal, or an unreadable local
                          record, when the node's manifest authenticates, belongs to this vault and its key slots equal
                          this device's copy. The ahead case discards changes made by any other publisher and asks first.
  --recover-slots         publish: unlock key slots this device knows nothing about (slots present, no manifest). Shows
                          their cost and asks before deriving.
  --allow-full-reupload   publish: allow uploading again more than 256 MiB of files the node no longer holds as recorded.
  --yes-abandon          abandon: confirm without typing the word (for scripts). Does not skip the backup and does
                          not touch the node.
  --show-request          Print each request (method, URL, headers) with credentials redacted.
  -h, --help              Show this help.

Environment (secrets belong here, not on the command line):
  IPFS_SYNC_RPC_URL, IPFS_SYNC_RPC_PORT, IPFS_SYNC_GATEWAY_URL, IPFS_SYNC_GATEWAY_PORT,
  IPFS_SYNC_MFS_ROOT, IPFS_SYNC_KEY
  IPFS_SYNC_AUTH_SCHEME, IPFS_SYNC_AUTH_USER, IPFS_SYNC_AUTH_PASSWORD, IPFS_SYNC_AUTH_TOKEN,
  IPFS_SYNC_AUTH_HEADER_NAME, IPFS_SYNC_AUTH_HEADER_VALUE
  IPFS_SYNC_PASSPHRASE_FILE, IPFS_SYNC_PASSPHRASE  (publish and pull: the vault passphrase; set at most one)
  IPFS_SYNC_DEVICE (publish: device name recorded in the manifest, default "cli"; the manifest carries "<name>-<first 12 hex of this device's id>")
  Per-endpoint auth override: IPFS_SYNC_RPC_AUTH_* or IPFS_SYNC_GATEWAY_AUTH_* (same suffixes).

Unlocking a vault (publish, pull): the passphrase comes from exactly one of IPFS_SYNC_PASSPHRASE_FILE (a file of mode 0600
that you own and that is not a symbolic link), IPFS_SYNC_PASSPHRASE, or, on a terminal when neither is set, a prompt
that does not echo. Setting both variables is an error, and text that is not a generated passphrase (wrong length,
characters outside A-Z and 2-7, failed check) is refused before any request. Exposure: an environment variable stays
readable by your other processes, is inherited by every child process started with it in the environment, can land
in shell history and CI logs, and the runtime may keep copies of it; the
CLI cannot prevent that. Use the prompt for interactive work and the 0600 file for automation. The CLI overwrites the
passphrase bytes it holds after key derivation, on a best-effort basis (strings cannot be overwritten).

Precedence: flags > environment > config file > defaults.

Exit codes: 0 ok, 1 a check, publish or pull failed, 2 usage, unsafe configuration or a refused pull destination
(no request is sent). For pull, 1 also means: a file failed verification or was not fetched, a path was skipped as unsafe
(a name another platform can write, or a path no honest publisher produces), or the pull stopped at a check (wrong
passphrase, rollback, fork, a held lock, a first pull that was not confirmed); 0 also covers paths skipped as expected
(a configuration folder or an excluded path from an older build's manifest).
`;
