import { sha256 } from "@noble/hashes/sha2.js";
import { concatBytes, utf8, wipe, type Bytes } from "./bytes";
import { CryptoError } from "./errors";
import { randomSymbolBytes, secureRandom, type RandomSource } from "./random";

/*
 * Generated passphrases (spec: key-slots, "Generated passphrases only, with a check").
 * A passphrase is 25 symbols of the uppercase RFC 4648 base32 alphabet: 23 random symbols (115 bits) followed
 * by 2 check symbols. The check is the first 10 bits of SHA-256 over the UTF-8 label and the 23 ASCII body
 * symbols, as two 5-bit symbols, most significant first. The check is NOT secret: it lets an interface say
 * "probable typo" without any request. It catches a mistyped body symbol with probability about 99.9%
 * (1 - 1/1024) and a mistyped check symbol always; about 1 in 1,024 arbitrary 25-symbol strings pass by
 * chance, so this is a typo and accident guard, not proof that the text was generated.
 */
export const PASSPHRASE_ALPHABET = "ABCDEFGHIJKLMNOPQRSTUVWXYZ234567";
export const PASSPHRASE_BODY_SYMBOLS = 23;
export const PASSPHRASE_CHECK_SYMBOLS = 2;
export const PASSPHRASE_LENGTH = PASSPHRASE_BODY_SYMBOLS + PASSPHRASE_CHECK_SYMBOLS;
export const PASSPHRASE_GROUP_SIZE = 5;
export const PASSPHRASE_CHECK_LABEL = "ipfs-sync/passphrase/check/v1";
/** Longer input is refused before it is scanned. */
export const PASSPHRASE_INPUT_MAX_BYTES = 256;

const HYPHEN = 0x2d;
const SPACE = 0x20;

declare const canonicalBrand: unique symbol;

/**
 * The 25 uppercase ASCII symbols that are the KDF input. Produced only by `canonicalizePassphrase*`,
 * `generatePassphrase` and `assertCanonicalPassphrase`; key-slot creation and unlock accept nothing else, and
 * re-check the bytes at run time, so a cast cannot smuggle in an empty or user-chosen secret.
 */
export type CanonicalPassphrase = Bytes & { readonly [canonicalBrand]: true };

declare const generatedBrand: unique symbol;

/**
 * A passphrase produced by `generatePassphrase` in this process. Vault CREATION accepts nothing else (unlock accepts
 * any canonical passphrase), so a user-chosen secret cannot found a vault. Enforced by type and by a registry.
 */
export type GeneratedPassphrase = CanonicalPassphrase & { readonly [generatedBrand]: true };

const GENERATED = new WeakSet<object>();

/** @internal only generatePassphraseWith and the test-only src/crypto/testing/generated-passphrase.ts may call it. */
export function markGenerated(passphrase: CanonicalPassphrase): GeneratedPassphrase {
  GENERATED.add(passphrase);
  return passphrase as GeneratedPassphrase;
}

/** Run-time proof that a passphrase is canonical AND was generated here; used at the entry of vault creation. */
export function assertGenerated(candidate: Uint8Array): GeneratedPassphrase {
  assertCanonicalPassphrase(candidate);
  if (!GENERATED.has(candidate)) throw new PassphraseFormatError("not-generated");
  return candidate as GeneratedPassphrase;
}

function brand(bytes: Bytes): CanonicalPassphrase {
  return bytes as CanonicalPassphrase;
}

export type PassphraseFailure = "length" | "alphabet" | "check" | "not-generated";

/** The text is not a valid generated passphrase. `reason` is public; the message never contains the text. */
export class PassphraseFormatError extends CryptoError {
  readonly reason: PassphraseFailure;

  constructor(reason: PassphraseFailure) {
    const detail =
      reason === "check"
        ? "the check symbols do not match (probable typo)"
        : reason === "not-generated"
          ? "only a passphrase generated by this product can create a vault"
        : reason === "alphabet"
          ? "it contains a character outside A-Z and 2-7"
          : "it does not have exactly 25 symbols";
    super("passphrase-format", `not a valid generated passphrase: ${detail}`);
    this.name = "PassphraseFormatError";
    this.reason = reason;
  }
}

/** The two check symbols (ASCII bytes) for 23 uppercase body symbols. */
export function computePassphraseCheck(body: Uint8Array): Bytes {
  const input = concatBytes(utf8(PASSPHRASE_CHECK_LABEL), body);
  const digest = sha256(input);
  wipe(input);
  const first = digest[0] ?? 0;
  const second = digest[1] ?? 0;
  const out = new Uint8Array([
    PASSPHRASE_ALPHABET.charCodeAt(first >> 3),
    PASSPHRASE_ALPHABET.charCodeAt(((first & 0x07) << 2) | (second >> 6)),
  ]);
  wipe(digest);
  return out;
}

/** A new passphrase as 25 canonical ASCII bytes, drawn from the platform CSPRNG. The caller wipes them after use. */
export function generatePassphrase(): GeneratedPassphrase {
  return generatePassphraseWith(secureRandom);
}

/** Test-only variant with injected randomness. Not exported from the public index. */
export function generatePassphraseWith(random: RandomSource): GeneratedPassphrase {
  const body = randomSymbolBytes(random, PASSPHRASE_BODY_SYMBOLS, PASSPHRASE_ALPHABET);
  const passphrase = concatBytes(body, computePassphraseCheck(body));
  wipe(body);
  return markGenerated(brand(passphrase));
}

/**
 * Run-time proof that bytes are a canonical passphrase (25 uppercase symbols with a valid check). Used at the
 * entry of key-slot creation and unlock; raises `passphrase-format` for anything else, before any derivation.
 */
export function assertCanonicalPassphrase(candidate: Uint8Array): CanonicalPassphrase {
  const canonical = canonicalizePassphrase(candidate);
  const same = canonical.length === candidate.length && canonical.every((byte, index) => byte === candidate[index]);
  wipe(canonical);
  if (!same) throw new PassphraseFormatError("alphabet");
  return brand(candidate as Bytes);
}

/** Display form: 5 groups of 5 separated by hyphens, e.g. `HEZVI-DN7IB-GLQIX-B5L7V-ARDHC`. The result is a string and cannot be zeroed. */
export function formatPassphrase(canonical: Uint8Array): string {
  if (canonical.length !== PASSPHRASE_LENGTH) throw new PassphraseFormatError("length");
  const text = String.fromCharCode(...canonical);
  const groups: string[] = [];
  for (let i = 0; i < PASSPHRASE_LENGTH; i += PASSPHRASE_GROUP_SIZE) groups.push(text.slice(i, i + PASSPHRASE_GROUP_SIZE));
  return groups.join("-");
}

function upperSymbol(byte: number): number | undefined {
  if (byte >= 0x41 && byte <= 0x5a) return byte;
  if (byte >= 0x61 && byte <= 0x7a) return byte - 0x20;
  if (byte >= 0x32 && byte <= 0x37) return byte;
  return undefined;
}

/**
 * The one canonical-passphrase function, used at setup and at unlock: remove hyphens (U+002D) and spaces
 * (U+0020), upper-case, require exactly 25 characters in `A-Z2-7` and a valid check. Returns the 25 uppercase
 * ASCII bytes that are the KDF input; anything else raises `passphrase-format` before any derivation.
 * Input is UTF-8 bytes; any non-ASCII byte is outside the alphabet and is refused. The caller wipes both arrays.
 */
export function canonicalizePassphrase(input: Uint8Array): CanonicalPassphrase {
  if (input.length > PASSPHRASE_INPUT_MAX_BYTES) throw new PassphraseFormatError("length");
  const symbols = new Uint8Array(PASSPHRASE_LENGTH);
  let count = 0;
  let tooLong = false;
  for (const byte of input) {
    if (byte === HYPHEN || byte === SPACE) continue;
    const symbol = upperSymbol(byte);
    if (symbol === undefined) {
      wipe(symbols);
      throw new PassphraseFormatError("alphabet");
    }
    if (count === PASSPHRASE_LENGTH) tooLong = true;
    else symbols[count++] = symbol;
  }
  if (tooLong || count !== PASSPHRASE_LENGTH) {
    wipe(symbols);
    throw new PassphraseFormatError("length");
  }
  const body = symbols.subarray(0, PASSPHRASE_BODY_SYMBOLS);
  const check = computePassphraseCheck(body);
  const valid = check[0] === symbols[PASSPHRASE_BODY_SYMBOLS] && check[1] === symbols[PASSPHRASE_BODY_SYMBOLS + 1];
  if (!valid) {
    wipe(symbols);
    throw new PassphraseFormatError("check");
  }
  return brand(symbols);
}

/** Canonicalise text typed or pasted into an interface. The intermediate bytes are overwritten; the string itself cannot be. */
export function canonicalizePassphraseText(text: string): CanonicalPassphrase {
  if (text.length > PASSPHRASE_INPUT_MAX_BYTES) throw new PassphraseFormatError("length");
  const bytes = utf8(text);
  try {
    return canonicalizePassphrase(bytes);
  } finally {
    wipe(bytes);
  }
}
