// Delta-gate (review-2b) fixes: N2-06, N2-08, N2-09, N2-10, N2-11.
import { mkdtemp, mkdir, rm, writeFile } from "node:fs/promises";
import { tmpdir } from "node:os";
import { join } from "node:path";
import { describe, expect, it, vi } from "vitest";

const sha = vi.hoisted(() => ({ inputs: [] as Uint8Array[] }));
vi.mock("@noble/hashes/sha2.js", async (importOriginal) => {
  const original = await importOriginal<typeof import("@noble/hashes/sha2.js")>();
  const wrapped = ((data: Uint8Array) => (sha.inputs.push(data), original.sha256(data))) as typeof original.sha256;
  Object.assign(wrapped, original.sha256);
  return { ...original, sha256: wrapped };
});

import {
  CryptoError,
  KdfCostRefusedError,
  canonicalizePassphraseText,
  createKeySlots,
  generatePassphrase,
  parseKeySlots,
  serializeKeySlots,
  unlockKeySlots,
  unlockKeySlotsBytes,
  utf8,
  type CanonicalPassphrase,
  type GeneratedPassphrase,
} from "../../src/crypto";
import { computePassphraseCheck } from "../../src/crypto/passphrase";
import { checkDistBundles } from "../../tools/hook-isolation.mjs";
import { countingFakeKdf, createWithFakeKdf, FLOOR_PARAMS, referencePassphrase, unlockBytesWith } from "../vectors/slot-helpers";

async function code(promise: Promise<unknown>): Promise<string> {
  try {
    await promise;
  } catch (error) {
    return error instanceof CryptoError ? error.code : `raw:${String(error)}`;
  }
  return "no-error";
}

describe("N2-06: the check input buffer is wiped", () => {
  it("the concatenated label and body handed to SHA-256 is all zero afterwards", () => {
    sha.inputs.length = 0;
    computePassphraseCheck(utf8("HEZVIDN7IBGLQIXB5L7VARD"));
    expect(sha.inputs).toHaveLength(1);
    expect(sha.inputs[0]?.length).toBe("ipfs-sync/passphrase/check/v1".length + 23);
    expect(sha.inputs[0]?.every((byte) => byte === 0)).toBe(true);
  });
});

describe("N2-10: only a generated passphrase creates a vault", () => {
  it("createKeySlots refuses a canonicalised (typed-in) passphrase with passphrase-format, before the KDF", async () => {
    const typed = canonicalizePassphraseText("HEZVI-DN7IB-GLQIX-B5L7V-ARDHC") as unknown as GeneratedPassphrase;
    const error = await createKeySlots({ passphrase: typed, params: FLOOR_PARAMS }).catch((e: unknown) => e);
    expect(error).toBeInstanceOf(CryptoError);
    expect((error as CryptoError).code).toBe("passphrase-format");
    expect((error as Error).message).toContain("generated by this product");
  });

  it("accepts the output of generatePassphrase(), and unlock accepts the same secret typed back in", async () => {
    const generated = generatePassphrase();
    const created = await createKeySlots({ passphrase: generated, params: FLOOR_PARAMS });
    const typedBack: CanonicalPassphrase = canonicalizePassphraseText(String.fromCharCode(...generated).toLowerCase());
    const unlocked = await unlockKeySlotsBytes(created.bytes, typedBack);
    expect(unlocked.keys.vaultId).toBe(created.keys.vaultId);
  }, 60_000);

  it("a copy of a generated passphrase is not generated (the mark is on the object)", async () => {
    const generated = generatePassphrase();
    const copy = new Uint8Array(generated) as unknown as GeneratedPassphrase;
    expect(await code(createKeySlots({ passphrase: copy, params: FLOOR_PARAMS }))).toBe("passphrase-format");
  });
});

describe("N2-08: platform checks come before any prompt; the refusal is structured", () => {
  const HIGH = { m: 98_304, t: 3, p: 1 };

  it("with crypto.subtle missing, approveCost is never called and the error is crypto-unavailable", async () => {
    const fake = countingFakeKdf();
    const created = await createWithFakeKdf(fake, referencePassphrase(), HIGH);
    const approve = vi.fn(async () => true);
    const baseline = fake.calls();
    vi.stubGlobal("crypto", { getRandomValues: crypto.getRandomValues.bind(crypto), subtle: undefined });
    try {
      expect(await code(unlockBytesWith(created.bytes, referencePassphrase(), fake, { costPolicy: { approveCost: approve } }))).toBe("crypto-unavailable");
    } finally {
      vi.unstubAllGlobals();
    }
    expect(approve).not.toHaveBeenCalled();
    expect(fake.calls()).toBe(baseline);
  });

  it("a failing self-test also comes before the prompt", async () => {
    const fake = countingFakeKdf();
    const created = await createWithFakeKdf(fake, referencePassphrase(), HIGH);
    const approve = vi.fn(async () => true);
    const { unlockKeySlotsInternal } = await import("../../src/crypto/key-slots");
    const failing = async (): Promise<void> => {
      throw new CryptoError("self-test-failed", "stub");
    };
    expect(await code(unlockKeySlotsInternal({ document: parseKeySlots(created.bytes), passphrase: referencePassphrase(), costPolicy: { approveCost: approve } }, { kdf: fake.kdf, selfTest: failing }))).toBe("self-test-failed");
    expect(approve).not.toHaveBeenCalled();
  });

  it("KdfCostRefusedError lists every tried slot above the limit, and prompting is up-front for all of them", async () => {
    const fake = countingFakeKdf();
    const created = await createWithFakeKdf(fake, referencePassphrase(), HIGH);
    const doc = parseKeySlots(created.bytes);
    const two = serializeKeySlots({ ...doc, slots: [doc.slots[0], doc.slots[0]] as unknown as typeof doc.slots });
    const baseline = fake.calls();
    const asked: unknown[] = [];
    const error = await unlockBytesWith(two, referencePassphrase(), fake, { costPolicy: { approveCost: async (p) => (asked.push(p), false) } }).catch((e: unknown) => e);
    expect(error).toBeInstanceOf(KdfCostRefusedError);
    expect((error as KdfCostRefusedError).slots).toEqual([HIGH, HIGH]);
    expect(asked).toEqual([HIGH]);
    expect(fake.calls()).toBe(baseline);
    expect(await code(unlockKeySlots({ document: parseKeySlots(two), passphrase: referencePassphrase() }))).toBe("kdf-cost-refused");
  });
});

describe("N2-09 and N2-11: parsed documents are deeply frozen and unforgeable", () => {
  it("every level of a parsed document, including unknown slots, is frozen", async () => {
    const fake = countingFakeKdf();
    const created = await createWithFakeKdf(fake);
    const doc = parseKeySlots(created.bytes);
    const withUnknown = parseKeySlots(serializeKeySlots({ ...doc, slots: [...doc.slots, { type: "future", raw: { type: "future", nested: { list: [1, { a: 2 }] } } }] }));
    const slot = withUnknown.slots[0] as unknown as { kdf: object; wrap: object };
    const unknown = withUnknown.slots[1] as unknown as { raw: { nested: { list: unknown[] } } };
    for (const value of [withUnknown, withUnknown.slots, slot, slot.kdf, slot.wrap, unknown, unknown.raw, unknown.raw.nested, unknown.raw.nested.list, unknown.raw.nested.list[1]]) {
      expect(Object.isFrozen(value)).toBe(true);
    }
    expect(() => {
      (slot.kdf as { m: number }).m = 1;
    }).toThrowError(TypeError);
  });

  it("structuredClone, Proxy and Object.create copies of a parsed document are refused", async () => {
    const fake = countingFakeKdf();
    const created = await createWithFakeKdf(fake);
    const doc = parseKeySlots(created.bytes);
    const before = fake.calls();
    for (const forged of [structuredClone(doc), new Proxy(doc, {}), Object.create(doc), { ...doc }, JSON.parse(JSON.stringify(doc))]) {
      const { unlockKeySlotsInternal } = await import("../../src/crypto/key-slots");
      expect(await code(unlockKeySlotsInternal({ document: forged, passphrase: referencePassphrase() }, { kdf: fake.kdf }))).toBe("invalid-argument");
    }
    expect(fake.calls()).toBe(before);
  });
});

describe("N2-11: the emitted-artifact check catches a planted sentinel", () => {
  it("checkDistBundles fails on a dist file that contains a test-only sentinel and reports missing artifacts", async () => {
    const root = await mkdtemp(join(tmpdir(), "hook-iso-"));
    try {
      await mkdir(join(root, "src/crypto/testing/nested"), { recursive: true });
      await writeFile(join(root, "src/crypto/testing/a.ts"), 'export const S = "IPFS_SYNC_TEST_ONLY_SENTINEL_A_1";\n');
      await writeFile(join(root, "src/crypto/testing/nested/b.ts"), 'export const S = "IPFS_SYNC_TEST_ONLY_SENTINEL_B_2";\n');
      const missing = await checkDistBundles({ root });
      expect(missing.ok).toBe(true);
      expect(missing.missing).toHaveLength(2);
      await mkdir(join(root, "dist/plugin"), { recursive: true });
      await writeFile(join(root, "dist/plugin/main.js"), 'var x = "IPFS_SYNC_TEST_ONLY_SENTINEL_B_2";\n');
      const planted = await checkDistBundles({ root });
      expect(planted.ok).toBe(false);
      expect(planted.violations).toEqual(["dist/plugin/main.js contains the sentinel of src/crypto/testing/nested/b.ts"]);
      expect(planted.checked).toEqual(["dist/plugin/main.js"]);
      expect(planted.missing).toHaveLength(1);
    } finally {
      await rm(root, { recursive: true, force: true });
    }
  });
});
