// mvp-07a task 3.1a: fold key, generated table header and body hash, and the generator script.
import { spawnSync } from "node:child_process";
import { createHash } from "node:crypto";
import { existsSync, mkdtempSync, readFileSync, writeFileSync } from "node:fs";
import { tmpdir } from "node:os";
import { join } from "node:path";
import { fileURLToPath } from "node:url";
import { describe, expect, it } from "vitest";
import { foldKey } from "../../src/sync/path-fold";
import { CASE_FOLD_ENTRIES, DEFAULT_IGNORABLE_RANGES, PATH_FOLD_UNICODE_VERSION } from "../../src/sync/path-fold-table";

const repoFile = (relative: string): string => fileURLToPath(new URL(`../../${relative}`, import.meta.url));
const TABLE_PATH = repoFile("src/sync/path-fold-table.ts");
const GENERATOR_PATH = repoFile("tools/gen-path-fold-table.mjs");
const BODY_MARKER = "// ---- body (sha256 above covers every byte after this line) ----\n";

interface Vectors {
  readonly unicodeVersion: string;
  readonly vectors: readonly { readonly name: string; readonly input: string; readonly key: string }[];
  readonly protected: readonly { readonly name: string; readonly key: string; readonly aliases: readonly string[] }[];
  readonly notProtected: readonly string[];
}
const vectors = JSON.parse(readFileSync(repoFile("tests/vectors/path-fold.json"), "utf8")) as Vectors;

const sha256 = (data: string): string => createHash("sha256").update(data, "utf8").digest("hex");

function splitTable(text: string): { header: string; body: string } {
  const at = text.indexOf(BODY_MARKER);
  if (at < 0) throw new Error("table has no body marker");
  return { header: text.slice(0, at), body: text.slice(at + BODY_MARKER.length) };
}
const headerField = (header: string, pattern: RegExp): string | undefined => pattern.exec(header)?.[1];

describe("fold key vectors", () => {
  for (const vector of vectors.vectors) {
    it(`${vector.name}`, () => expect(foldKey(vector.input)).toBe(vector.key));
  }

  it("named spec cases reach the protected key", () => {
    expect(foldKey(".ıpfs-sync")).toBe(".ipfs-sync");
    expect(foldKey(".İpfs-sync")).toBe(".ipfs-sync");
    expect(foldKey(".ipfſ-sync")).toBe(".ipfs-sync");
  });

  for (const protectedName of vectors.protected) {
    for (const alias of protectedName.aliases) {
      it(`${JSON.stringify(alias)} equals ${protectedName.name}`, () => {
        expect(foldKey(alias)).toBe(protectedName.key);
        expect(foldKey(alias)).toBe(foldKey(protectedName.name));
      });
    }
  }

  it("ordinary names keep keys that differ from every protected key", () => {
    const protectedKeys = new Set(vectors.protected.map((entry) => entry.key));
    for (const name of vectors.notProtected) expect(protectedKeys.has(foldKey(name))).toBe(false);
    expect(foldKey(".gitignore")).toBe(".gitignore");
    expect(foldKey("notes/ipfs-sync.md")).toBe("notes/ipfs-sync.md");
  });

  it("is idempotent over every vector input and key", () => {
    for (const vector of vectors.vectors) {
      expect(foldKey(vector.key)).toBe(vector.key);
      expect(foldKey(foldKey(vector.input))).toBe(foldKey(vector.input));
    }
  });

  it("vector file names the table's Unicode version", () => expect(vectors.unicodeVersion).toBe(PATH_FOLD_UNICODE_VERSION));
});

describe("generated table", () => {
  const { header, body } = splitTable(readFileSync(TABLE_PATH, "utf8"));

  it("header records the Unicode version, each source hash and the body hash", () => {
    expect(headerField(header, /^\/\/ unicode-version: (\S+)$/m)).toBe(PATH_FOLD_UNICODE_VERSION);
    expect(headerField(header, /^\/\/ source CaseFolding\.txt sha256: ([0-9a-f]{64})$/m)).toBeDefined();
    expect(headerField(header, /^\/\/ source DerivedCoreProperties\.txt sha256: ([0-9a-f]{64})$/m)).toBeDefined();
    expect(headerField(header, /^\/\/ body-sha256: ([0-9a-f]{64})$/m)).toBeDefined();
    expect(header).toMatch(/^\/\/ GENERATED by tools\/gen-path-fold-table\.mjs\. Do not edit by hand/);
  });

  it("body matches the recorded body hash", () => {
    expect(sha256(body)).toBe(headerField(header, /^\/\/ body-sha256: ([0-9a-f]{64})$/m));
  });

  it("a modified body fails the hash check", () => {
    const recorded = headerField(header, /^\/\/ body-sha256: ([0-9a-f]{64})$/m);
    const tamperedEntry = body.replace("[0x0049, [0x0069]]", "[0x0049, [0x0068]]");
    const tamperedVersion = body.replace(`"${PATH_FOLD_UNICODE_VERSION}"`, '"0.0.0"');
    expect(tamperedEntry).not.toBe(body);
    expect(tamperedVersion).not.toBe(body);
    expect(sha256(tamperedEntry)).not.toBe(recorded);
    expect(sha256(tamperedVersion)).not.toBe(recorded);
  });

  it("holds the entries the supplement and vectors depend on, and no U+0131 entry", () => {
    const fold = new Map(CASE_FOLD_ENTRIES);
    expect(fold.get(0x0130)).toEqual([0x69, 0x307]);
    expect(fold.get(0x017f)).toEqual([0x73]);
    expect(fold.get(0x212a)).toEqual([0x6b]);
    expect(fold.get(0x1e9e)).toEqual([0x73, 0x73]);
    expect(fold.has(0x0131)).toBe(false);
  });

  it("ignorable ranges are sorted and disjoint and include the joiner and soft hyphen", () => {
    let previousEnd = -1;
    for (const [first, last] of DEFAULT_IGNORABLE_RANGES) {
      expect(first).toBeGreaterThan(previousEnd);
      expect(last).toBeGreaterThanOrEqual(first);
      previousEnd = last;
    }
    const contains = (codePoint: number): boolean => DEFAULT_IGNORABLE_RANGES.some(([first, last]) => codePoint >= first && codePoint <= last);
    expect(contains(0x200d)).toBe(true);
    expect(contains(0x00ad)).toBe(true);
    expect(contains(0x0041)).toBe(false);
  });
});

describe("generator script", () => {
  const generator = readFileSync(GENERATOR_PATH, "utf8");
  const fixtureCaseFolding = [
    "# CaseFolding-17.0.0.txt",
    "0041; C; 0061; # LATIN CAPITAL LETTER A",
    "0049; T; 0131; # T line, skipped",
    "00DF; S; 1E9E; # S line, skipped",
    "00DF; F; 0073 0073; # LATIN SMALL LETTER SHARP S",
    "",
  ].join("\n");
  const fixtureDerived = [
    "# DerivedCoreProperties-17.0.0.txt",
    "00AD          ; Default_Ignorable_Code_Point # Cf       SOFT HYPHEN",
    "200B..200F    ; Default_Ignorable_Code_Point # Cf   [5] ZERO WIDTH SPACE..RIGHT-TO-LEFT MARK",
    "2010..2011    ; Default_Ignorable_Code_Point # merged into the previous range",
    "0041..005A    ; Alphabetic # not ignorable",
    "",
  ].join("\n");

  function run(out: string, dir: string, overrides: Partial<Record<string, string>> = {}) {
    const args = {
      "unicode-version": "17.0.0",
      "case-folding": join(dir, "CaseFolding.txt"),
      "case-folding-sha256": sha256(fixtureCaseFolding),
      "derived-core": join(dir, "DerivedCoreProperties.txt"),
      "derived-core-sha256": sha256(fixtureDerived),
      out,
      ...overrides,
    };
    const flat = Object.entries(args).flatMap(([flag, value]) => [`--${flag}`, value as string]);
    return spawnSync(process.execPath, [GENERATOR_PATH, ...flat], { encoding: "utf8" });
  }

  function fixtureDir(): string {
    const dir = mkdtempSync(join(tmpdir(), "path-fold-gen-"));
    writeFileSync(join(dir, "CaseFolding.txt"), fixtureCaseFolding);
    writeFileSync(join(dir, "DerivedCoreProperties.txt"), fixtureDerived);
    return dir;
  }

  it("keeps only statuses C and F, merges adjacent ranges and is byte-identical on a second run", () => {
    const dir = fixtureDir();
    const first = run(join(dir, "a.ts"), dir);
    const second = run(join(dir, "b.ts"), dir);
    expect(first.status).toBe(0);
    expect(second.stdout.replace("b.ts", "a.ts")).toBe(first.stdout);
    const a = readFileSync(join(dir, "a.ts"), "utf8");
    expect(a).toBe(readFileSync(join(dir, "b.ts"), "utf8"));
    const { header, body } = splitTable(a);
    expect(headerField(header, /^\/\/ source CaseFolding\.txt sha256: (\S+)$/m)).toBe(sha256(fixtureCaseFolding));
    expect(headerField(header, /^\/\/ source DerivedCoreProperties\.txt sha256: (\S+)$/m)).toBe(sha256(fixtureDerived));
    expect(headerField(header, /^\/\/ body-sha256: (\S+)$/m)).toBe(sha256(body));
    expect(body).toContain("[0x0041, [0x0061]]");
    expect(body).toContain("[0x00DF, [0x0073, 0x0073]]");
    expect(body).not.toContain("0x0131");
    expect(body).not.toContain("0x1E9E");
    expect(body).toContain("[0x200B, 0x2011]");
    expect(body).not.toContain("0x0041, 0x005A");
  });

  it("refuses a source whose sha256 differs from the pinned hash", () => {
    const dir = fixtureDir();
    const result = run(join(dir, "c.ts"), dir, { "case-folding-sha256": "0".repeat(64) });
    expect(result.status).not.toBe(0);
    expect(result.stderr).toMatch(/does not match the pinned/);
    expect(existsSync(join(dir, "c.ts"))).toBe(false);
  });

  it("refuses a source of another Unicode version", () => {
    const dir = fixtureDir();
    const result = run(join(dir, "d.ts"), dir, { "unicode-version": "16.0.0" });
    expect(result.status).not.toBe(0);
    expect(result.stderr).toMatch(/first line/);
  });

  it("never imports the generated file", () => {
    expect(generator).not.toMatch(/^\s*import\b[^;]*path-fold-table/m);
    expect(generator).not.toMatch(/\bimport\(|\brequire\(/);
  });

  const ucdDir = process.env.PATH_FOLD_UCD_DIR;
  it.skipIf(ucdDir === undefined)("regenerates the checked-in table byte-for-byte from the pinned Unicode files (PATH_FOLD_UCD_DIR)", () => {
    const { header } = splitTable(readFileSync(TABLE_PATH, "utf8"));
    const dir = mkdtempSync(join(tmpdir(), "path-fold-real-"));
    const out = join(dir, "regenerated.ts");
    const result = spawnSync(
      process.execPath,
      [
        GENERATOR_PATH,
        "--unicode-version", PATH_FOLD_UNICODE_VERSION,
        "--case-folding", join(ucdDir!, "CaseFolding.txt"),
        "--case-folding-sha256", headerField(header, /^\/\/ source CaseFolding\.txt sha256: (\S+)$/m)!,
        "--derived-core", join(ucdDir!, "DerivedCoreProperties.txt"),
        "--derived-core-sha256", headerField(header, /^\/\/ source DerivedCoreProperties\.txt sha256: (\S+)$/m)!,
        "--out", out,
      ],
      { encoding: "utf8" },
    );
    expect(result.status).toBe(0);
    expect(readFileSync(out, "utf8")).toBe(readFileSync(TABLE_PATH, "utf8"));
  });
});
